title: Dfarmácias
description: 'A lightweight, backend-free ecommerce solution.'
baseurl: /iDrugs
price: 20
weight: 2
designer: Gabriel Barros
type: Ótimo
condition: Excelente




# Jekll-Store Front
image_prefix: '/iDrugs/produtos/20/'
#image_prefix: 'http://res.cloudinary.com/jekyll-store/'

# http://openexchangerates.github.io/accounting.js/#documentation
accounting:
  symbol : 'R$'
  format: '%s%v'
  decimal : ','
  thousand: '.'
  precision : 2




prose:
  ignore:
    - _includes
    - _layouts
    - assets
    - json
    - node_modules
    - pages
    - .gitignore
    - _config.yml
    - CNAME
    - Gemfile
    - package.json
    - README.md
  metadata:
    _products:
      - name: name
        field:
          element: text
          label: Name
          help: Must be unique
      - name: price
        field:
          element: number
          label: 'Preço (R$)'
      - name: weight
        field:
          element: number
          label: 'Peso (kg)'
      - name: designer
        field:
          element: text
          label: Designer
      - name: type
        field:
          element: select
          label: Type
          options:
            - value: Wood
            - value: Metal
            - value: Metallic
      - name: condition
        field:
          element: select
          label: Condition
          options:
            - value: Mint
            - value: Worn
            - value: Rough
      - name: image
        field:
          element: text
          label: Image
      - name: big_image
        field:
          element: text
          label: Big Image

# http://jekyllrb.com/docs/configuration/
permalink: blog/:title
sass:
  sass_dir: /assets/_sass
  style:
collections:
  products:
    output: true
    permalink: /products/:path/

defaults:
   -
    scope:
      path: ''
      type: products
    values:
      layout: product
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - package.json
